name: Package for Linux
description: Create Linux packages for Bee Launcher

inputs:
  version:
    description: Launcher version
    required: true
  build-type:
    description: Type for the build
    required: true
    default: Debug
  artifact-name:
    description: Name of the uploaded artifact
    required: true
    default: Linux
  qt-version:
    description: Version of Qt to use
    required: true
  gpg-private-key:
    description: Private key for AppImage signing
    required: false
  gpg-private-key-id:
    description: ID for the gpg-private-key, to select the signing key
    required: false

runs:
  using: composite

  steps:
    - name: Cleanup Qt installation on Linux
      shell: bash
      run: |
        rm -rf "$QT_PLUGIN_PATH"/printsupport
        rm -rf "$QT_PLUGIN_PATH"/sqldrivers
        rm -rf "$QT_PLUGIN_PATH"/help
        rm -rf "$QT_PLUGIN_PATH"/designer
        rm -rf "$QT_PLUGIN_PATH"/qmltooling
        rm -rf "$QT_PLUGIN_PATH"/qmlls
        rm -rf "$QT_PLUGIN_PATH"/qmllint
        rm -rf "$QT_PLUGIN_PATH"/platformthemes/libqgtk3.so

    - name: Setup build variables
      shell: bash
      # values come from dpkg-architecture, not user input
      run: | # zizmor: ignore[github-env]
        # Fixup architecture naming for AppImages
        dpkg_arch="$(dpkg-architecture -q DEB_HOST_ARCH_CPU)"
        case "$dpkg_arch" in
          "amd64")
            APPIMAGE_ARCH="x86_64"
            ;;
          "arm64")
            APPIMAGE_ARCH="aarch64"
            ;;
          *)
            echo "# 🚨 The Debian architecture \"$deb_arch\" is not recognized!" >> "$GITHUB_STEP_SUMMARY"
            exit 1
            ;;
        esac
        echo "APPIMAGE_ARCH=$APPIMAGE_ARCH" >> "$GITHUB_ENV"

        # Used for the file paths of libraries
        echo "DEB_HOST_MULTIARCH=$(dpkg-architecture -q DEB_HOST_MULTIARCH)" >> "$GITHUB_ENV"

    - name: Package AppImage
      shell: bash
      env:
        VERSION: ${{ github.ref_type == 'tag' && github.ref_name || inputs.version }}
        BUILD_DIR: build
        BUILD_TYPE: ${{ inputs.build-type }}
        INSTALL_APPIMAGE_DIR: install-appdir
        REF_TYPE: ${{ github.ref_type }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}

        GPG_PRIVATE_KEY: ${{ inputs.gpg-private-key }}
        GPG_PRIVATE_KEY_ID: ${{ inputs.gpg-private-key-id }}
      run: |
        cmake --install "$BUILD_DIR" --config "$BUILD_TYPE" --prefix "$INSTALL_APPIMAGE_DIR"

        if [ "$GPG_PRIVATE_KEY_ID" != '' ]; then
          echo "$GPG_PRIVATE_KEY" > privkey.asc
          gpg --import privkey.asc
          gpg --export --armor "$GPG_PRIVATE_KEY_ID" > pubkey.asc
        else
          echo ":warning: Skipped code signing for Linux AppImage, as gpg key was not present." >> $GITHUB_STEP_SUMMARY
        fi

        sharun lib4bin \
          --hard-links \
          --with-hooks \
          --dst-dir "$INSTALL_APPIMAGE_DIR" \
          "$INSTALL_APPIMAGE_DIR"/bin/* "$QT_PLUGIN_PATH"/*/*.so

        cp ~/bin/AppImageUpdate.AppImage "$INSTALL_APPIMAGE_DIR"/bin/
        # FIXME(@getchoo): gamemode doesn't seem to be very portable with DBus. Find a way to make it work!
        find "$INSTALL_APPIMAGE_DIR" -name '*gamemode*' -exec rm {} +

        #disable OpenGL and Vulkan launcher features until https://github.com/VHSgunzo/sharun/issues/35
        echo "BEELAUNCHER_DISABLE_GLVULKAN=1" >> "$INSTALL_APPIMAGE_DIR"/.env
        #makes the launcher use portals for file picking
        echo "QT_QPA_PLATFORMTHEME=xdgdesktopportal" >> "$INSTALL_APPIMAGE_DIR"/.env
        ln -s org.beelauncher.BeeLauncher.metainfo.xml "$INSTALL_APPIMAGE_DIR"/share/metainfo/org.beelauncher.BeeLauncher.appdata.xml
        ln -s share/applications/org.beelauncher.BeeLauncher.desktop "$INSTALL_APPIMAGE_DIR"
        ln -s share/icons/hicolor/256x256/apps/org.beelauncher.BeeLauncher.png "$INSTALL_APPIMAGE_DIR"
        mv "$INSTALL_APPIMAGE_DIR"/{sharun,AppRun}
        ls -la "$INSTALL_APPIMAGE_DIR"

        if [[ "$REF_TYPE" == "tag" ]]; then
          APPIMAGE_DEST="BeeLauncher-Linux-$APPIMAGE_ARCH.AppImage"
        else
          APPIMAGE_DEST="BeeLauncher-Linux-$VERSION-$BUILD_TYPE-$APPIMAGE_ARCH.AppImage"
        fi

        mkappimage \
          --updateinformation "gh-releases-zsync|$REPO_OWNER|$REPO_NAME|latest|BeeLauncher-Linux-$APPIMAGE_ARCH.AppImage.zsync" \
          "$INSTALL_APPIMAGE_DIR" \
          "$APPIMAGE_DEST"

    - name: Package portable tarball
      shell: bash
      env:
        BUILD_DIR: build
        BUILD_TYPE: ${{ inputs.build-type }}
        INSTALL_PORTABLE_DIR: install-portable
      run: |
        cmake --install "$BUILD_DIR" --config "$BUILD_TYPE" --prefix "$INSTALL_PORTABLE_DIR"
        cmake --install "$BUILD_DIR" --config "$BUILD_TYPE" --prefix "$INSTALL_PORTABLE_DIR" --component portable

        sharun lib4bin \
          --with-hooks \
          --hard-links \
          --dst-dir "$INSTALL_PORTABLE_DIR" \
          "$INSTALL_PORTABLE_DIR"/bin/* "$QT_PLUGIN_PATH"/*/*.so

        # FIXME(@getchoo): gamemode doesn't seem to be very portable with DBus. Find a way to make it work!
        find "$INSTALL_PORTABLE_DIR" -name '*gamemode*' -exec rm {} +

        for l in $(find "$INSTALL_PORTABLE_DIR" -type f -o -type l); do l=${l#$(pwd)/}; l=${l#"$INSTALL_PORTABLE_DIR"/}; l=${l#./}; echo $l; done > "$INSTALL_PORTABLE_DIR"/manifest.txt
        cd "$INSTALL_PORTABLE_DIR"
        tar -czf ../BeeLauncher-portable.tar.gz *

    - name: Upload binary tarball
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: BeeLauncher-${{ inputs.artifact-name }}-Qt6-Portable-${{ inputs.version }}-${{ inputs.build-type }}
        path: BeeLauncher-portable.tar.gz

    - name: Upload AppImage
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: BeeLauncher-${{ runner.os }}-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.APPIMAGE_ARCH }}.AppImage
        path: BeeLauncher-${{ runner.os }}-*${{ env.APPIMAGE_ARCH }}.AppImage

    - name: Upload AppImage Zsync
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: BeeLauncher-${{ runner.os }}-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.APPIMAGE_ARCH }}.AppImage.zsync
        path: BeeLauncher-${{ runner.os }}-*${{ env.APPIMAGE_ARCH }}.AppImage.zsync
