---
name: Probe Update Flake

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    if: github.repository == 'Sudo-Ivan/BeeLauncher'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - uses: DeterminateSystems/flake-checker-action@4b90f9fc724969ff153fe1803460917c84fe00a3 # v5
      - uses: DeterminateSystems/update-flake-lock@a2bbe0274e3a0c4194390a1e445f734c597ebc37 # v24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-msg: "chore(nix): update flake.lock via CI/CD"
          pr-title: "chore(nix): update flake.lock"
          pr-labels: |
            chore
            nix
          git-author-name: github-actions[bot]
          git-author-email: 41898282+github-actions[bot]@users.noreply.github.com
          git-commiter-name: github-actions[bot]
          git-commiter-email: 41898282+github-actions[bot]@users.noreply.github.com
          pr-reviewers: |
            Sudo-Ivan
