# CI
name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: { }

jobs:
  build_release:
    name: Build Release
    uses: $/.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
    with:
      build-type: Release
      environment: Release
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PRIVATE_KEY_ID: ${{ secrets.GPG_PRIVATE_KEY_ID }}
      APPLE_CODESIGN_CERT: ${{ secrets.APPLE_CODESIGN_CERT }}
      APPLE_CODESIGN_PASSWORD: ${{ secrets.APPLE_CODESIGN_PASSWORD }}
      APPLE_CODESIGN_ID: ${{ secrets.APPLE_CODESIGN_ID }}
      APPLE_NOTARIZE_APPLE_ID: ${{ secrets.APPLE_NOTARIZE_APPLE_ID }}
      APPLE_NOTARIZE_TEAM_ID: ${{ secrets.APPLE_NOTARIZE_TEAM_ID }}
      APPLE_NOTARIZE_PASSWORD: ${{ secrets.APPLE_NOTARIZE_PASSWORD }}
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: "true"
          persist-credentials: false
          path: "BeeLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      - name: Grab and store version
        run: |
          tag_name="${GITHUB_REF_NAME}"
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv "$GITHUB_WORKSPACE"/BeeLauncher-source "BeeLauncher-$VERSION"
          mv BeeLauncher-Linux-Qt6-Portable*/BeeLauncher-portable.tar.gz "BeeLauncher-Linux-Qt6-Portable-$VERSION.tar.gz"
          mv BeeLauncher-Linux-aarch64-Qt6-Portable*/BeeLauncher-portable.tar.gz "BeeLauncher-Linux-aarch64-Qt6-Portable-$VERSION.tar.gz"
          mv BeeLauncher-*.AppImage/BeeLauncher-*-x86_64.AppImage BeeLauncher-Linux-x86_64.AppImage
          mv BeeLauncher-*.AppImage.zsync/BeeLauncher-*-x86_64.AppImage.zsync BeeLauncher-Linux-x86_64.AppImage.zsync
          mv BeeLauncher-*.AppImage/BeeLauncher-*-aarch64.AppImage BeeLauncher-Linux-aarch64.AppImage
          mv BeeLauncher-*.AppImage.zsync/BeeLauncher-*-aarch64.AppImage.zsync BeeLauncher-Linux-aarch64.AppImage.zsync
          mv BeeLauncher-macOS*/BeeLauncher.zip "BeeLauncher-macOS-$VERSION.zip"
          mv BeeLauncher-macOS*/BeeLauncher.dmg "BeeLauncher-macOS-$VERSION.dmg"

          tar --exclude='.git' -czf "BeeLauncher-$VERSION.tar.gz" "BeeLauncher-$VERSION"

          for d in BeeLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="BeeLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv BeeLauncher-*.exe "../${NAME}-Setup-${VERSION}.exe"
            test -n "${INST}" || zip -r -9 "../${NAME}-${VERSION}.zip" *
            cd ..
          done

          for d in BeeLauncher-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="BeeLauncher-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv BeeLauncher-*.exe "../${NAME}-Setup-${VERSION}.exe"
            test -n "${INST}" || zip -r -9 "../${NAME}-${VERSION}.zip" *
            cd ..
          done

          for d in BeeLauncher-Windows-MinGW-arm64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="BeeLauncher-Windows-MinGW-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv BeeLauncher-*.exe "../${NAME}-Setup-${VERSION}.exe"
            test -n "${INST}" || zip -r -9 "../${NAME}-${VERSION}.zip" *
            cd ..
          done

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --title "Bee Launcher $VERSION" \
            --draft \
            --verify-tag \
            "BeeLauncher-Linux-x86_64.AppImage" \
            "BeeLauncher-Linux-x86_64.AppImage.zsync" \
            "BeeLauncher-Linux-aarch64.AppImage" \
            "BeeLauncher-Linux-aarch64.AppImage.zsync" \
            "BeeLauncher-Linux-Qt6-Portable-$VERSION.tar.gz" \
            "BeeLauncher-Linux-aarch64-Qt6-Portable-$VERSION.tar.gz" \
            "BeeLauncher-Windows-MinGW-w64-$VERSION.zip" \
            "BeeLauncher-Windows-MinGW-w64-Portable-$VERSION.zip" \
            "BeeLauncher-Windows-MinGW-w64-Setup-$VERSION.exe" \
            "BeeLauncher-Windows-MinGW-arm64-$VERSION.zip" \
            "BeeLauncher-Windows-MinGW-arm64-Portable-$VERSION.zip" \
            "BeeLauncher-Windows-MinGW-arm64-Setup-$VERSION.exe" \
            "BeeLauncher-Windows-MSVC-arm64-$VERSION.zip" \
            "BeeLauncher-Windows-MSVC-arm64-Portable-$VERSION.zip" \
            "BeeLauncher-Windows-MSVC-arm64-Setup-$VERSION.exe" \
            "BeeLauncher-Windows-MSVC-$VERSION.zip" \
            "BeeLauncher-Windows-MSVC-Portable-$VERSION.zip" \
            "BeeLauncher-Windows-MSVC-Setup-$VERSION.exe" \
            "BeeLauncher-macOS-$VERSION.zip" \
            "BeeLauncher-macOS-$VERSION.dmg" \
            "BeeLauncher-$VERSION.tar.gz"
